INSERT INTO ebook
(`id`,
 `author`,
 `category`,
 `description`,
 `genre`,
 `price`,
 `publicity_year`,
 `publisher`,
 `quantity`,
 `title`,
 `extension`,
 `size`)
VALUES
  (10, "Gabriel García Márquez", "Ebooks", "Bassus magister diligenter prensionems lumen est.", "PN", 8.99, 1899,
       "Jonathan Cape", 50, "100 Years Of Solitude", "mobi", 2),
  (11, "Ernest Hemingway", "Ebooks", "Hilotaes ridetis!", "PN", 4.99, 1940, "Charles Scribner's Sons", 50,
       "For Whom the Bell Tolls", "epub", 20),
  (12, "Alexandre Dumas", "Ebooks", "Sunt musaes promissio regius, clemens elogiumes.", "EP", 7.65, 1845,
       "Pinguin Publishing", 50, "The Count Of Monte Christo", "epub", 2),
  (13, "Maynard Solomon", "Ebooks", "Pol, a bene abactor.", "Historical", 11.21, 2005, "George Allen & Unwin", 50,
       "Mozart",
       "epub", 2),
  (14, "Joseph Conrad", "Ebooks", "Castors unda!", "PN", 6.00, 1834, "Blackwood's Magazine", 50, "Heart Of Darkness",
       "AZW3",
   1),
  (15, "George Orwell", "Ebooks", "A falsis, gemna altus zirbus.", "Fantasy", 7.00, 1949, "Secker & Warburg", 50,
       "1984", "mobi", 2),
  (16, "Sir Arthur Conan Doyle", "Ebooks", "Prarere absolute ducunt ad fidelis adelphis.", "Fantasy", 12.99, 1902,
       "George Newnes", 50, "The Hound Of The Baskervilles",
       "mobi", 1),
  (17, "Frances Hodgson Burnett", "Ebooks", "Idoleums sunt elogiums de noster orgia.", "Fantasy", 27.12, 1911,
       "Heinemann", 50,
       "The Secret Garden", "AZW3", 2),
  (18, "Jane Austen", "Ebooks", "Est noster repressor, cesaris.", "Fantasy", 5.99, 1813,
       "Pinguin Publishing", 50,
       "Pride and Prejudice", "mobi", 3);