INSERT INTO audiobook
(`id`,
 `author`,
 `category`,
 `description`,
 `genre`,
 `price`,
 `publicity_year`,
 `publisher`,
 `quantity`,
 `title`,
 `audio_extension`,
 `duration_time`)
VALUES
  (19, "Sun Tzu", "Audiobooks", "Bassus magister diligenter prensionems lumen est.", "Historical", 8.99, -2000,
       "None", 50, "Art Of War", "MP3", 2),
  (20, "Richard Sharpe", "Audiobooks", "Hilotaes ridetis!", "Historical", 4.99, 1940, "Penguin Books", 50,
       "Waterloo", "WAV", 20),
  (21, "Marcel Proust", "Audiobooks", "Sunt musaes promissio regius, clemens elogiumes.", "PN", 7.65, 1845,
       "Grasset and Gallimard", 50, "In Search Of Lost Time", "WAV", 2),
  (22, "Dmitry Glukhovsky", "Audiobooks", "Pol, a bene abactor.", "Fantasy", 11.21, 2005, "Penguin Books", 50, "Futu.Re",
       "WAV", 2),
  (23, "William Shakespeare", "Audiobooks", "Castors unda!", "Fantasy", 6.00, 1834, "None",  50, "Romeo And Juliet", "CDA",
   1),
  (24, "J. R. R. Tolkien", "Audiobooks", "A falsis, gemna altus zirbus.", "Fantasy", 7.00, 1949, "George Allen & Unwin", 50,
       "The Return Of The King", "MP3", 2),
  (25, "Friedrich Nietzsche", "Audiobooks", "Prarere absolute ducunt ad fidelis adelphis.", "Fantasy", 12.99, 1902,
       "Ernst Schmeitzner", 50, "Thus Spoke Zarathustra",
       "MP3", 1),
  (26, "Dante Alighieri", "Audiobooks", "Idoleums sunt elogiums de noster orgia.", "Fantasy", 27.12, 1911, "Heinemann", 50,
       "Divine Comedy", "CDA", 2),
  (27, "Margaret Mitchell", "Audiobooks", "Est noster repressor, cesaris.", "Fantasy", 5.99, 1813,
       "Macmillan Publishers", 50,
       "Gone With The Wind", "MP3", 3);